### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by suho** [TKH219/nimble_assignment#10]
Hello Ha 👋, thank you for your effort on the code submission. I am Su, currently Engineering Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

**Comment by TKH219** [comment]
Hello Su,

Thank you for taking your time to review my assignment. Please let me know if you have any concerns about it.

**Comment by suho** [comment]
Hi @TKH219, sorry for the delay on the last issue. I've completed the code review round. Feel free to raise any concerns if you have

**Comment by suho** [comment]
@TKH219 I just checked all your comments! All solutions look good!

Apart from the last issue, which is not hard to resolve. Let's end the code review session.

Thanks for your effort!

**Comment by TKH219** [comment]
Hello @suho 
Thank you for it. If you need anything else, please let me know.
